CREATE TABLE IF NOT EXISTS `users` (
     `id` VARCHAR(36) UNIQUE PRIMARY KEY NOT NULL,
     `name` VARCHAR(120) NOT NULL,
     `email` VARCHAR(255) UNIQUE NOT NULL,
     `login` VARCHAR(50) UNIQUE NOT NULL,
     `password` VARCHAR(255) NOT NULL
)